### ISSUE TITLE
Override existing file with same name

### ISSUE THREAD

**Issue by gunjan1988** [velocityzen/dropbox-stream#15]
Hi,
I have a folder, inside which there is already an image with name 'display.jpg'.When the user uploads a new file , I want to update the existing one with new file(same name default.jpg). How can I achieve this?

Ii would be helpful, if you could tell me how to delete the existing file in the folder?

Thanks,
Gunjan Chhetri

**Comment by velocityzen** [comment]
Hi @gunjan1988 

To overwrite the existing files just use the `mode: "overwrite"` option. 
https://www.dropbox.com/developers/documentation/http/documentation#files-upload

This library is made to add a stream interface to the Dropbox upload/download APIs. To make any other not streaming API calls check the [Dropbox API documentation](https://www.dropbox.com/developers/documentation).

Cheers
