### ISSUE TITLE
buffer is undefined when callback calls progress function

### ISSUE THREAD

**Issue by sschoebinger** [velocityzen/dropbox-stream#2]
the function `uploadFinish` in upload.js calls the `progress` function in the callback of the api call. Once this callback is executed the buffer can already be undefined. This causes an error.

What is the reason to call the progress function once the api call for uploadFinish was successful?

It seems there is already a fork which fixes this issue: https://github.com/wxt2005/dropbox-stream
Would be great to see this fix in npm sources.

**Comment by velocityzen** [comment]
@sschoebinger do you use the latest version? That bug was fixed couple weeks ago. If you still have that problem can you post the code and file size you're trying to upload

**Comment by sschoebinger** [comment]
@velocityzen thanks for the fast response.

I'm using `"dropbox-stream": "^1.0.4",`.
File size is around 100 to 200KB.

The code which uses the dropbox-stream module does the following:
Receive data from a browser via web socket, encode it as wav and store it via dropbox-stream in a dropbox folder.

This is the main part of the code which is related to the dropbox-stream module:
`upStream = dropboxStream.createDropboxUploadStream({
					token: DROPBOX_TOKEN,
					filepath: ("/"+(vawFileName)),
					chunkSize: 4 * 1024,
					autorename: true
				})
				.on('done', res => console.log('Success', res))
				.on('progress', res => console.log("Progress", res))
				.on('error', err => console.log(err));
				wavWriter.pipe(upStream);`

Each time when the web socket receives new data it passes it to the dropbox-stream. Once the connection from web socket is closed I call `wavWriter.end()` to close the streams.

Locally I tested by removing the line 134 `this.progress();` from file `upload.js` which solved my problem.

**Comment by velocityzen** [comment]
@sschoebinger Done! Get update from npm!
