### ISSUE TITLE
Feature request 'progress' event for the Download stream

### ISSUE THREAD

**Issue by MohammedAl-Mahdawi** [velocityzen/dropbox-stream#4]
Hi,

I used the total file size and the `.on('progress', res => console.log(res))` event to calculate the uploaded percentage.

I wish if there is the same thing for the Download stream as well.

All the best,
Mohammed

**Comment by velocityzen** [comment]
v2.0.0
Added progress event. 
Updated events names to be more consistent. Check the readme.
👍

**Comment by MohammedAl-Mahdawi** [comment]
@velocityzen WOW, Thank you so much!
