### ISSUE TITLE
Using sharing/get_shared_link_file

### ISSUE THREAD

**Issue by dseeker** [velocityzen/dropbox-stream#8]
I just tested downloading a 10GB file and it works perfectly, nice!
Is there any way to make streaming function for files shared via urls?

The official library uses writeFile, but trying to get 10GB files blows up the memory in node and crashes the aplication.
```
dbx.sharingGetSharedLinkFile({ url: result.sharedLink })
    .then(function (data) {
      fs.writeFile(data.name, data.fileBinary, 'binary', function (err) {
```

**Comment by velocityzen** [comment]
Hmm, interesting use case, let me check it.

**Comment by velocityzen** [comment]
@dseeker I published v3 with download from shared links support. Also I changed the `filepath` option to just `path` everywhere so don't forget to update that. 
Tell me if it works for you!
